# Generated by Django 5.2.1 on 2025-05-31 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.IntegerField()),
                ('category', models.CharField(choices=[('exterior', 'exterior'), ('interior', 'interior'), ('suspension', 'suspension'), ('engine', 'engine'), ('drivetrain', 'drivetrain')], default='exterior')),
                ('description', models.CharField(max_length=1000)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.vehicle')),
            ],
        ),
    ]
