# Generated by Django 5.2.1 on 2025-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mileage',
            field=models.PositiveIntegerField(),
        ),
    ]
